version: '3.4'
services:
  api:
    build:
      context: .
    container_name: zssn_api
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: zssn
      POSTGRES_USER: zssn
      POSTGRES_PASSWORD: zssn123
    depends_on:
      - db
      # - redis

  # redis:
  #   image: "redis:7-alpine"
  #   ports:
  #     - 6379
  #   volumes:
  #     - ./tmp/redis_data:/var/lib/redis/data

  db:
    image: postgres:16
    container_name: zssn_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - zssn_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: zssn
      POSTGRES_USER: zssn
      POSTGRES_PASSWORD: zssn123
  
volumes:
  zssn_volume:
    name: zssn_volume
