version: '3.4'
services:
  api:
    image: adrield/zssn:latest
    container_name: zssn_api
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://zssn:zssn123@db:5432/zssn_development
      - RAILS_ENV=production
    depends_on:
      - db
      # - redis

  # redis:
  #   image: "redis:7-alpine"
  #   ports:
  #     - 6379
  #   volumes:
  #     - ./tmp/redis_data:/var/lib/redis/data

  db:
    image: postgres:16
    container_name: zssn_db
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: zssn_development
      POSTGRES_USER: zssn
      POSTGRES_PASSWORD: zssn123
