
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: zssn
  password: zssn123

development:
  <<: *default
  database: zssn_development

test:
  <<: *default
  database: zssn_test

production:
  <<: *default
  database: zssn
